using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAdmin.Infrastructure.Models
{
    [Table("mpats_Organisation")]
    public class Organisation
    {
        public string SchemaIdentifier { get; set; }
        [Key]
        public int OrganisationID { get; set; }
        public int? ParentOrganisationID { get; set; }
        public string OrganisationPassword { get; set; }
        public string OrganisationIdentifier { get; set; }
        public string OrganisationName { get; set; }
        public bool TestAccount { get; set; }
        public bool JobBoardOwner { get; set; }
        public DateTime? ContractEndDate { get; set; }
        public DateTime? TrialStartDate { get; set; }
        public byte? OrganisationStatusID { get; set; }
        public short? OrganisationTZID { get; set; }
        public string OrganisationCultureID { get; set; }
        public byte? FeatureATS { get; set; }
        public byte? FeatureMP { get; set; }
        public byte? FeatureIntegrate { get; set; }
        public byte? FeatureFailAllPostings { get; set; }
        public byte? FeatureAuthoriseToPost { get; set; }
        public byte? FeatureForceDisclaimer { get; set; }
        public byte? FeatureAllOptionalFields { get; set; }
        public string Region { get; set; }
        public int? PasswordExpirationDays { get; set; }
        public int? MaxUsers { get; set; }
        public string ApplicationURLPlaceHolder { get; set; }
        public string ApplicationURLSuffix { get; set; }
        public string IPAccessCSVList { get; set; }
        public byte? PostingResultsEmail { get; set; }
        public string PostingResultsEmailAddress { get; set; }
        public byte? PostingExpireEmail { get; set; }
        public string PostingExpireEmailAddress { get; set; }
        public byte? PostingResultsDailyEmail { get; set; }
        public string PostingResultsDailyEmailAddress { get; set; }
        public byte? PostingResultsDailyEmailFormat { get; set; }
        public byte? PostingResultsWeeklyEmail { get; set; }
        public string PostingResultsWeeklyEmailAddress { get; set; }
        public byte? PostingResultsWeeklyEmailFormat { get; set; }
        public byte? PostingResultsMonthlyEmail { get; set; }
        public string PostingResultsMonthlyEmailAddress { get; set; }
        public byte? PostingResultsMonthlyEmailFormat { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostCode { get; set; }
        public string MainContactName { get; set; }
        public string MainContactPhone { get; set; }
        public string MainContactFax { get; set; }
        public string MainContactEmail { get; set; }
        public string WebSite { get; set; }
        public DateTime CreateDate { get; set; }
        public int? CreateUserID { get; set; }
        public DateTime? UpdateDate { get; set; }
        public int? UpdateUserID { get; set; }
        public DateTime? DeleteDate { get; set; }
        public int? DeleteUserID { get; set; }
        public string catsone_subdomain { get; set; }
        public string catsone_transaction_code { get; set; }
        public byte? FeatureCVSearch { get; set; }
        public byte? FeatureCVAggregate { get; set; }
        public byte? FeatureCATS { get; set; }
        public string DisclaimerPermanent { get; set; }
        public string DisclaimerContract { get; set; }
        public int? QuotaUsedResetTriggerID { get; set; }
        public byte? FeatureImpersonateOwningUser { get; set; }
        public byte? FeatureNoAdvertCreate { get; set; }
        public byte? FeatureNoAdvertActions { get; set; }
        public byte? FeatureNoExpressPost { get; set; }
        public byte? FeatureNoQuickPost { get; set; }
        public byte? FeatureNoTemplate { get; set; }
        public short? FeatureDefaultAdvertRows { get; set; }
        public short? FeatureDefaultCandidateRows { get; set; }
        public short? FeatureDefaultOffsetDate { get; set; }
        public byte? FeaturePostFeedSelectionDisplay { get; set; }
        public int? CVDatabaseID { get; set; }
        public byte? FeatureCVDatabase { get; set; }
        public Nullable<bool> noTrigger { get; set; }
        public byte? IndeedOrganic { get; set; }
        public byte? FeatureHidePostings { get; set; }
        public byte? FeatureNoCVSearch { get; set; }
        public byte? FeatureNoEditPost { get; set; }
        public byte? FeatureNoReporting { get; set; }
        public byte? FeaturePerFeedFields { get; set; }
        public byte? FeatureWorkflow { get; set; }
        public int? DefaultOrganisationWorkflowID { get; set; }
        public byte? FeatureNoCandidateActions { get; set; }
        public int? WatchDogsAllowedPerUser { get; set; }
        public string DefaultViewer { get; set; }
        public byte? FeatureAdvertMove { get; set; }
        public byte? FeatureOrganisationMove { get; set; }
        public byte? FeatureUserMove { get; set; }
        public string DefaultLoginController { get; set; }
        public string DefaultLoginAction { get; set; }
        public byte? IsResourcingPod { get; set; }
        public byte? FeatureAdvertNotes { get; set; }
        public string OrganisationLogoURL { get; set; }
        public int? OrganisationLogoWidth { get; set; }
        public int? OrganisationLogoHeight { get; set; }
        public string TrackingURLBase { get; set; }
        public int? AccountAdminUserID { get; set; }
        public string WelcomeText { get; set; }
        public byte? HolderOfThirdPartyClients { get; set; }
        public byte? FeatureCRM { get; set; }
        public byte? FeatureAdvertAllocateUsers { get; set; }
        public byte? FeatureAddApplication { get; set; }
        public byte? FeatureCandidateMove { get; set; }
        public byte? FeatureFormWorkflow { get; set; }
        public byte? FeatureTrackClicks { get; set; }
        public byte? EmailDelayID { get; set; }
        public byte? FeatureHideCandidatePersonalDetails { get; set; }
        public byte? FeatureHideEqualOpportunities { get; set; }
        public string DefaultSiteID { get; set; }
        public byte? PostingExpirePreEmail { get; set; }
        public string PostingExpirePreEmailAddress { get; set; }
        public byte? FeatureCopyReplyMessages { get; set; }
        public byte? FeatureInterviewAcceptNotify { get; set; }
        public byte? FeatureFavourites { get; set; }
        public byte? FeatureApplicationAttachments { get; set; }
        public string WhiteLabelDomain { get; set; }
        public string WhiteLabelSiteName { get; set; }
        public string WhiteLabelSiteContactEmail { get; set; }
        public byte? FeatureCandidateEdit { get; set; }
        public byte? FeatureCandidateEditName { get; set; }
        public byte? FeatureArchiveAdvertAfterAllExpired { get; set; }
        public string CVDatabaseDefaultXSL { get; set; }
        public byte? FeatureRemoveOnClose { get; set; }
        public byte? FeatureIsCorporate { get; set; }
        public byte? FeatureForceHTTPS { get; set; }
        public int? FeatureMaxExportRows { get; set; }
        public byte? FeatureInterviewBooking { get; set; }
        public byte? FeatureThomasInternational { get; set; }
        public byte? FeatureTalentQ { get; set; }
        public byte? FeatureTheNeedle { get; set; }
        public byte? FeatureVideoInterview { get; set; }
        public string ThomasInternationalAgentGUID { get; set; }
        public string ThomasInternationalAuthToken { get; set; }
        public string TalentQAPIUser { get; set; }
        public string TalentQAPIPassword { get; set; }
        public byte? FeatureISVGroup { get; set; }
        public string ISVGroupSecurityToken { get; set; }
        public string ISVGroupLLCID { get; set; }
        public string ISVGroupTLCID { get; set; }
        public byte? FeatureSignable { get; set; }
        public string SignableAPIKey { get; set; }
        public string SignableUserID { get; set; }
        public string TheNeedleAPIServerURL { get; set; }
        public string TheNeedleAPIKey { get; set; }
        public string TheNeedleFixedAccountKey { get; set; }
        public byte? TheLaddersOrganic { get; set; }
        public byte? CareerJetOrganic { get; set; }
        public byte? GlassDoorOrganic { get; set; }
        public byte? FeatureSMS { get; set; }
        public int? SMSProviderID { get; set; }
        public string SMSMobileNumber { get; set; }
        public int? OfficeID { get; set; }
        public byte[] OrganisationVersion { get; set; }
        public byte? FeatureAutoHideDeletedUser { get; set; }

        [ForeignKey("OrganisationStatusID")]
        public virtual OrganisationStatus OrganisationStatus { get; set; }
    }
}